shared: &shared
  - ".github/**"
  - ".nvmrc"
  - "assets/**"
  - "build-scripts/**"
docker:
  - *shared
  - Dockerfile
rust:
  - *shared
  - "*.toml"
  - ".cargo/**"
  - "backend-end/**"
  - Cargo.lock
typescript:
  - *shared
  - "**/*.ts"
  - "**/*.mjs"
  - "front-end/**"
  - "package.json"
  - "package-lock.json"
